import { Class } from '../../models/Class';
import { User } from '../../models/User';
import { AppError } from '../../middlewares/errorHandler';
import mongoose from 'mongoose';

interface CreateClassInput {
  name: string;
  academicYear: string;
  course: string;
  teacherId: string;
}

export class ClassroomService {
  async createClass(input: CreateClassInput) {
    const { name, academicYear, course, teacherId } = input;

    // Verify teacher exists
    const teacher = await User.findById(teacherId);
    if (!teacher || teacher.role !== 'TEACHER') {
      throw new AppError('Invalid teacher', 400);
    }

    const classData = await Class.create({
      name,
      academicYear,
      course,
      teacherId: new mongoose.Types.ObjectId(teacherId),
      students: []
      // joinCode will be auto-generated by pre-save hook
    });

    return {
      id: classData._id.toString(),
      name: classData.name,
      academicYear: classData.academicYear,
      course: classData.course,
      joinCode: classData.joinCode,
      teacherId: classData.teacherId.toString()
    };
  }

  async getClassById(classId: string) {
    const classData = await Class.findById(classId)
      .populate('teacherId', 'email name')
      .populate('students', 'email name');
    
    if (!classData) {
      throw new AppError('Class not found', 404);
    }

    return {
      id: classData._id.toString(),
      name: classData.name,
      academicYear: classData.academicYear,
      course: classData.course,
      joinCode: classData.joinCode,
      teacher: classData.teacherId,
      students: classData.students
    };
  }

  async joinClassByCode(joinCode: string, studentId: string) {
    const classData = await Class.findOne({ joinCode });
    if (!classData) {
      throw new AppError('Invalid join code', 404);
    }

    const student = await User.findById(studentId);
    if (!student || student.role !== 'STUDENT') {
      throw new AppError('Invalid student', 400);
    }

    if (classData.students.includes(new mongoose.Types.ObjectId(studentId))) {
      throw new AppError('Student already in class', 400);
    }

    classData.students.push(new mongoose.Types.ObjectId(studentId));
    await classData.save();

    return {
      message: 'Successfully joined class',
      classId: classData._id.toString(),
      className: classData.name
    };
  }

  async joinClass(classId: string, studentId: string) {
    const classData = await Class.findById(classId);
    if (!classData) {
      throw new AppError('Class not found', 404);
    }

    const student = await User.findById(studentId);
    if (!student || student.role !== 'STUDENT') {
      throw new AppError('Invalid student', 400);
    }

    if (classData.students.includes(new mongoose.Types.ObjectId(studentId))) {
      throw new AppError('Student already in class', 400);
    }

    classData.students.push(new mongoose.Types.ObjectId(studentId));
    await classData.save();

    return {
      message: 'Successfully joined class',
      classId: classData._id.toString()
    };
  }

  async getStudents(classId: string) {
    const classData = await Class.findById(classId).populate('students', 'email name role');
    if (!classData) {
      throw new AppError('Class not found', 404);
    }

    return classData.students.map((student: any) => ({
      id: student._id.toString(),
      email: student.email,
      name: student.name,
      role: student.role
    }));
  }

  async getTeacherClasses(teacherId: string) {
    const classes = await Class.find({ teacherId: new mongoose.Types.ObjectId(teacherId) })
      .populate('students', 'name email')
      .sort({ createdAt: -1 });

    return classes.map(classData => ({
      _id: classData._id.toString(),
      name: classData.name,
      academicYear: classData.academicYear,
      course: classData.course,
      joinCode: classData.joinCode,
      students: classData.students.length,
      createdAt: classData.createdAt
    }));
  }

  async getStudentClasses(studentId: string) {
    const classes = await Class.find({
      students: new mongoose.Types.ObjectId(studentId)
    })
      .populate('teacherId', 'name email')
      .sort({ createdAt: -1 });

    return classes.map(classData => ({
      _id: classData._id.toString(),
      name: classData.name,
      academicYear: classData.academicYear,
      course: classData.course,
      teacher: classData.teacherId,
      createdAt: classData.createdAt
    }));
  }
}
